### ISSUE TITLE
Default DB connection

### ISSUE THREAD

**Issue by vaclavn** [iamdevice/codeception-multidb#4]
It would be nice if one defined connection was the default so all tests working with the first connection still work without any change.

I can imagine ugly solution to make the connection called `primary` always the default. Or adding a new parameter to make the connection default.

```
modules:
    config:
        MultiDb:
            connections:
                primary:
                    dsn: 'mysql:host=mysql;port=3306;dbname=test_db'
                    user: '...'
                    password: '...'
                    primary: true
```

I can prepare pull-request if you like the idea.
